version: "3.1"
services:

    home_report:
        build: .
        environment:
            - INFLUXDB_USER=writer
            - INFLUXDB_USER_PASSWORD=xxxxxx
            - INFLUXDB_HOST=www.craigwarren.co.uk
            - INFLUXDB_PORT=8086
            - NEST_TOKEN=xxxx
        secrets:
            - nest_token
            - source: influxdb_write_user_password
              target: influx_pass



secrets:
    nest_token:
        file: ./secrets/nest_token
    influxdb_admin_password:
        file: ./secrets/influxdb_admin_password
    influxdb_read_user_password:
        file: ./secrets/influxdb_read_user_password
    influxdb_write_user_password:
        file: ./secrets/influxdb_write_user_password
