version: "3.1"
services:
    grafana:
        image: grafana/grafana:5.0.4
        ports:
            - 3000:3000
        volumes:
            - /mnt/volume-lon1-01/grafana:/var/lib/grafana:z
            - /etc/letsencrypt/:/etc/.ssh/:z
            - ./grafana.ini:/etc/grafana/grafana.ini:z
